version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - clamav

  clamav:
    image: "mk0x/docker-clamav"
    ports:
      - "3310:3310"
